plugins {
	id 'java'
	id 'org.springframework.boot' version '3.4.3'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.favicon'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(17)
	}
}

repositories {
	google()
	mavenCentral()
}

dependencies {
	implementation group: 'org.glassfish.tyrus.bundles', name: 'tyrus-standalone-client', version: '1.10'
//	implementation group: 'javax.websocket', name: 'javax.websocket-api', version: '1.1'
//	implementation group: 'org.glassfish.tyrus', name: 'tyrus-server', version: '1.1'
//	implementation group: 'org.glassfish.tyrus', name: 'tyrus-client', version: '1.1'
//	implementation group: 'org.glassfish.tyrus', name: 'tyrus-container-grizzly', version: '1.1'
	implementation 'com.slack.api:bolt:1.39.0'
	implementation 'com.slack.api:bolt-socket-mode:1.39.0'
	implementation 'javax.websocket:javax.websocket-api:1.1'
	implementation 'org.hibernate.validator:hibernate-validator:8.0.1.Final'
	implementation 'jakarta.validation:jakarta.validation-api:3.0.2'
//	implementation 'com.google.auth:google-auth-library-oauth2-http:1.14.0' // Google OAuth 라이브러리
	implementation 'com.slack.api:bolt-servlet:1.39.0'
	implementation 'com.slack.api:bolt-jetty:1.39.0'
	implementation 'org.springdoc:springdoc-openapi-starter-webmvc-ui:2.0.2'
	implementation 'org.springframework.boot:spring-boot-starter-oauth2-client'
	implementation 'org.springframework.boot:spring-boot-starter-security'
	compileOnly 'org.projectlombok:lombok:1.18.28'
	annotationProcessor 'org.projectlombok:lombok:1.18.28'
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}


tasks.named('test') {
	useJUnitPlatform()
}