spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
slack.app.token=${SLACK_APP_TOKEN}
slack.bot.token=${SLACK_BOT_TOKEN}
slack.webhook.url=${SLACK_WEBHOOK_URL}
slack.signing.secret=${SLACK_SIGNING_SECRET}
